### ISSUE TITLE
Consistent Variables

### ISSUE THREAD

**Issue by sarahmehmedi** [tbrown2/comp_330_project_1#1]
I liked how the tests were separated into different classes, this made it very organized and easier to read/understand. One thing I came across in tweet.java, the variables should be changed so that it is consistent. 
ex:
line 81:`ArrayList<linkables> getURLs()
`
line 83:`ArrayList<linkables> mentionList = new ArrayList<linkables>();
`
line 89: `mentionList.add(linkableList.get(i));
`
line 92: `mentionList.add(linkableList.get(i));
`
The mentionList should be changed to URLList or something that is consistent with the function, same thing for getHashtags function.

**Comment by tbrown2** [comment]
I modified my code heavily and cut a lot of classes. This issue is resolved now. Thank you for your input Sarah!
