### ISSUE TITLE
Overly Complex

### ISSUE THREAD

**Issue by ConnorMacDonell** [tbrown2/comp_330_project_1#2]
Reading through your code I am seeing a bit of overcomplexity. I think that this code can be written more efficiently while still achieving your goals. My suggestion would be to look for ways you can simplify your project.

**Comment by jthompson18** [comment]
I'd get rid of the unnecessary classes. You don't need classes for hashtag, or mentions. They have no unique attributes. Making them classes adds no value. It just adds more overhead to the program.

**Comment by tbrown2** [comment]
I would agree, wasn't sure if later that these classes would have more to them later on. But for the sake of this project, I definitely should scale back.

**Comment by tbrown2** [comment]
Got rid of all the unnecessary classes. Thank you for your advice!
