### ISSUE TITLE
Compartments

### ISSUE THREAD

**Issue by joehernandez11** [tbrown2/comp_330_project_1#3]
Very lovely compartments! I like how everything has its own segment from the classes to the tests! Very easy to read and follow. I like how towards the end of the files, I want to say the parser file, you started commenting in-depth and explaining what is going on in your code. This is excellent and my eye and mind thank you for it. If I can make a tiny suggestion, I would try extending the comments to the rest of your code. Although most of your classes are small and easy to understand one in particular was little long and had several methods and could use a comment or two just to help anyone evaluating or reviewing your code to follow your train of thought or understand what the intent was. I always forget to comment as well. I just get carried away with the code.

**Comment by tbrown2** [comment]
Joe, I have gone ahead and commented further on the rest of my code. Thank you for all your nice comments. YOU DA BEST.
