### ISSUE TITLE
Regex Usage

### ISSUE THREAD

**Issue by dallen4** [tbrown2/comp_330_project_1#4]
As someone who used regex's themselves, I liked that you used regex's to identify URLs. However, I noticed that your functions for identifying hashtags and mentions were _significantly_ longer and was wondering what made you decide to not use a regex for each of those to simplify the process. As I found in my project, if you use a regex for each type of tweet entity you can even compartmentalize functionality more and just swap out one regex for the appropriate one you want to test for.

**Comment by tbrown2** [comment]
Took your advice and used regex's, It not only made my code simpler, it also functions more consistently than my previous method. Thank you for raising the issue!
