### ISSUE TITLE
use .gitignore to avoid committing compiled code

### ISSUE THREAD

**Issue by sshilpika** [tbrown2/comp_330_project_1#5]
You should make sure that you don't commit files that can be generated from files that are already committed.

[Github best practices](https://gist.github.com/SethRobertson/1540906/68feeabfe906ec1eb893e4fa45f402795ed6e62c#dont)

**Comment by tbrown2** [comment]
As per your advice I added a gitignore file, and to the best of my knowledge, got rid of all the files that should not be used in version control.
