### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by louiehernandez95** [tbrown2/comp_330_project_1#6]
First off by looking at your code I can see that you have a lot of classes. At first I thought it would be a problem but then I though that because majority are test classes it should be easier. Especially pinpointing possible problems. You should go on and expand your code to include a user class. If there was one suggestion I can give is to write more comments for your code.

**Comment by tbrown2** [comment]
Thank you for raising these issues, if we expand on the scope of this project, I will definitely consider adding a user class to my code. I have gone ahead and written more comments in my code as per your suggestion, and will be closing this issue out.
