### ISSUE TITLE
Code Suggestions

### ISSUE THREAD

**Issue by leandrohss** [tbrown2/comp_330_project_1#7]
Hi there!
Follows some suggestion for your code:

**1.    General Suggestions:**
1.1.    Capitalize the first letter of each class, it's a Java convention (http://www.oracle.com/technetwork/java/codeconventions-135099.html)
1.2.    Separate your code and tests in different packages
1.3.    You should use Encapsulation in your code. That basically means attributes as private and methods as public, according to their scope, of course.

**2.     **\* Class linkables *****
2.1 The constructor receives “s”, “l” and “t”.  I'd suggest you to use more meaningful names.
2.2 You could change the method “getLocation()” to “getStartLocation()”. It’s easier to understand

**3.    **\* Class Tweet *****
3.1. In the method “isDelete”, you could just use this: “return isDeleted;”
3.2. Try to use Foreach instead of the Regular For in the methods getMentions, getHashtag and getURLs

In general, the code is working well. Congrats!

**Comment by tbrown2** [comment]
I have followed your advice and done all issues raised minus 1.1, but I will make sure to keep that convention in mind when working on other java applications. Thank you for all the helpful suggestions!
